### ISSUE TITLE
Banned from using whatsapp

### ISSUE THREAD

**Issue by github838** [Zodt/ChatApi#3]
![image](https://user-images.githubusercontent.com/78624931/127560956-fa936816-5ee0-409a-a78e-9c3b2b2bfc7f.jpeg)

**Comment by Zodt** [comment]
Contact to support Chat-api service.
| Messager | Contact |
|:------------:|:----------:|
|Telegram | @Chat_API_Support |
|WhatsApp | +17162266665 |
