### ISSUE TITLE
[Question] Caption Info

### ISSUE THREAD

**Issue by ZemeckisPT** [Zodt/ChatApi#7]
Hi, first of all congratulations for this project, it has helped me a lot and it is very well structured and clean. Amazing job!
I have a question here, I am not able to get the Caption information from the received image when I use, for example, GetMessagesHistory, the IMessage interface does not have this property, Caption.
How can I get this information or it will be in a future release?
Thanks :)

**Comment by Zodt** [comment]
I think it's maybe a bug. 
If that true, I will try to fix it in the next patch.
Thank you for your question

**Comment by Zodt** [comment]
Yes, it's a bug. In next couple days I'll try to fix it.

```
{
      "id": "true_79001111112@c.us_3EB0002300010F059A3B",
      "body": "https://s3.eu-central-1.wasabisys.com/incoming-chat-api/2021/2/18/210169/2b5f47b5-77c8-4317-ae99-feae310b5005.txt",
      "fromMe": true,
      "self": 1,
      "isForwarded": 0,
      "author": "79001111111@c.us",
      "time": 1556029868,
      "chatId": "79001111112@c.us",
      "messageNumber": 8011,
      "type": "document",
      "senderName": "Роман Воронцов",
      **"caption": "caption text"**,
      "quotedMsgBody": null,
      "quotedMsgId": null,
      "quotedMsgType": null,
      "metadata": null,
      "ack": null,
      "chatName": "testChat1"
}
```

**Comment by cb7754** [comment]
HI Zodt,
I tried to compile several  example but I couldn't find the reference: 
using ChatApiClient.Properties;
Could you help me?
Thanks :)

**Comment by Zodt** [comment]
> HI Zodt, I tried to compile several example but I couldn't find the reference: using ChatApiClient.Properties; Could you help me? Thanks :)

Hi, can you create a new [GitHub Issue](https://github.com/Zodt/ChatApi/issues/new/choose) with more detalization of your problem?
