### ISSUE TITLE
Cannot Compile Examples 

### ISSUE THREAD

**Issue by cb7754** [Zodt/ChatApi#8]
I installed the the libraries you provided and those compile without any error. 

But when I tried an example took from your documentation , for instance :  https://github.com/Zodt/ChatApi/blob/Release/Documentation/en-EN/WhatsApp/ChatApi.WA.Messages/Operations/SendTextMessage.md, I couldn't compile.

I used VS 2019 and I added all the reference but the last one(ChataApiClients) because I couldn't find in your libraries
The code is below and the when compiler throw an error was marked with // ---->

```
using System;

using ChatApi.Core.Connect;
using ChatApi.Core.Connect.Interfaces;

using ChatApi.WA.Messages;
using ChatApi.WA.Messages.Collections;

using ChatApi.WA.Messages.Requests;
using ChatApi.WA.Messages.Requests.Interfaces;

using ChatApiClient.Properties;            //----> I couldn't add this one (I don't know where it is)

namespace ChatApiClient
{
    internal class Program
    {
        internal static IWhatsAppConnect Connect { get; set; }

        internal static void Main()
        {
            // put your chat-api's data
            Connect = new WhatsAppConnect(WhatsApp_Server, WhatsApp_Instance, WhatsApp_Token);        // ----> compiler couldn't 
find these varaibles
            IMessagesOperation messageOperation = new MessagesOperation(Connect);
            
            ITextMessageRequest textMessage = new TextMessageRequest
            {
                Phone = "79001111111",
                Message = "Test TextMessage"    // ----> compiler couldn't find Message
             };

            var chatApiResponse = messageOperation.SendTextMessage(request);    //---->  compiler couldn't find request
            if (!chatApiResponse.IsSuccess) throw chatApiResponse.Exception!;     //----> compiler couldn't find chatApiResponse.Exception

            var response = chatApiResponse.GetResult();
            Console.WriteLine(response?.PrintMembers());      // ----> compiler couldn't findPrintMembers
        }
    }
}
```

Could you tell me where is the library ChatApiClient?.
Thanks a lot!

**Comment by Zodt** [comment]
@cb7754 yea, you're right. I wrote this document in a hurry, so there were typos in it.
The correct version of the code is below

```csharp
using ChatApi.Core.Connect;
using ChatApi.Core.Connect.Interfaces;

using ChatApi.WA.Messages;
using ChatApi.WA.Messages.Requests;
using ChatApi.WA.Messages.Requests.Interfaces;

namespace ChatApiClient
{
    internal class Program
    {
        internal static IWhatsAppConnect Connect { get; set; }

        internal static void Main()
        {
            // put your chat-api's data
            Connect = new WhatsAppConnect("WhatsApp_Server", "WhatsApp_Instance", "WhatsApp_Token");
            IMessagesOperation messageOperation = new MessagesOperation(Connect);
            
            ITextMessageRequest request = new TextMessageRequest
            {
                Phone = "79001111111",
                Body = "Test TextMessage"
            };

            var chatApiResponse = messageOperation.SendTextMessage(request);
            if (!chatApiResponse.IsSuccess) throw chatApiResponse.Exception!;

            var response = chatApiResponse.GetResult();
            Console.WriteLine(response?.PrintMembers());
        }
    }
}
```

or

``` csharp
using ChatApi.Core.Connect;
using ChatApi.Core.Connect.Interfaces;
using ChatApi.WA.Messages;
using ChatApi.WA.Messages.Requests;
using ChatApi.WA.Messages.Requests.Interfaces;

IWhatsAppConnect connect = new WhatsAppConnect("WhatsApp_Server", "WhatsApp_Instance", "WhatsApp_Token");
IMessagesOperation messageOperation = new MessagesOperation(connect);

ITextMessageRequest request = new TextMessageRequest
{
    Phone = "79001111111",
    Body = "Test TextMessage"
};

var chatApiResponse = messageOperation.SendTextMessage(request);
if (!chatApiResponse.IsSuccess) throw chatApiResponse.Exception!;

var response = chatApiResponse.GetResult();
Console.WriteLine(response?.PrintMembers());
```

**Comment by cb7754** [comment]
Zodt, some questions
In the same example of Send Message, I have two errors in these lines of codes:

`var chatApiResponse = messageOperation.SendTextMessage(request);    ----> request does not exist in the current context`

and in this one:
`Console.WriteLine(response?.PrintMembers()); ----> IMessageResponse does not contain a definition for PrintMembers() `

Another question: where do you get these values:
"WhatsApp_Server", "WhatsApp_Instance", "WhatsApp_Token"
in th line:
`IWhatsAppConnect connect = new WhatsAppConnect("WhatsApp_Server", "WhatsApp_Instance", "WhatsApp_Token");`

Thanks for your help!
Carlos

**Comment by Zodt** [comment]
> Another question: where do you get these values: "WhatsApp_Server", "WhatsApp_Instance", "WhatsApp_Token" in th line: `IWhatsAppConnect connect = new WhatsAppConnect("WhatsApp_Server", "WhatsApp_Instance", "WhatsApp_Token");`

> Zodt, some questions In the same example of Send Message, I have two errors in these lines of codes:
> `var chatApiResponse = messageOperation.SendTextMessage(request); ----> request does not exist in the current context`
> and in this one: `Console.WriteLine(response?.PrintMembers()); ----> IMessageResponse does not contain a definition for PrintMembers() `

You need sign in on the [ChatApi service](https://chat-api.com/es/).
Then, when you obtained account preferences (Server, Instance, Token), put them on the new instance of `WhatsAppConnect`.

**Comment by cb7754** [comment]
Zodt, what about rhese errors:

`var chatApiResponse = messageOperation.SendTextMessage(request); ----> request does not exist in the current context`
`and in this one: Console.WriteLine(response?.PrintMembers()); ----> IMessageResponse does not contain a definition for `PrintMembers()`

Thanks for your help!
Carlos

**Comment by Zodt** [comment]
> Zodt, what about rhese errors:
> 
> `var chatApiResponse = messageOperation.SendTextMessage(request); ----> request does not exist in the current context` `and in this one: Console.WriteLine(response?.PrintMembers()); ----> IMessageResponse does not contain a definition for `PrintMembers()`
> 
> Thanks for your help! Carlos

Since you did not specify the token, server and instance, the request to the server cannot be executed => nothing will be printed and an exception will be thrown
